/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.teamX.server;

import java.net.*;
import java.io.*;
//import edu.duke.ece651.teamX.shared.MyName;
import edu.duke.ece651.teamX.shared.*;

public class App {

  RiscServer rs;

  // string to greet the clients to the game
  static String GREETING = "Welcome to the Game of Risc. Before we begin, we need some information to set up the game.\n\n";

  // string to get the number of players
  static String PLAYER_PROMPT = "How many players are playing? Our current system supports 2,3, and 4.\n";

  public App(RiscServer rs) {
    this.rs = rs;
  }

  private Integer welcomePhase() {
    System.out.println(GREETING + PLAYER_PROMPT);
    String numPlayers = System.console().readLine();
    return Integer.parseInt(numPlayers);
  }

  public static void main(String[] args) throws IOException {
    RiscServer rs = new RiscServer(new ServerSocket(5000));
    App a = new App(rs);
    Integer numPlayers = a.welcomePhase();
    rs.run();
  }
}
