/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.teamX.client;

import java.io.IOException;
import java.net.*;

import edu.duke.ece651.teamX.shared.*;

public class App {

  private RiscClient rc;

  public App(RiscClient rc) {
    this.rc = rc;
  }

  public static void main(String[] args) throws IOException {
    try {
      RiscClient rc = new RiscClient(new Socket(InetAddress.getLocalHost(), 5000));
      App a = new App(rc);
      rc.run();
    } catch (UnknownHostException e) {
      e.printStackTrace();
    }
  }
}
