/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.teamX.client;

import java.io.IOException;
import java.net.*;

import edu.duke.ece651.teamX.shared.*;

public class App {

  private RiscClient rc;

  /**
   * This function is to initalize the client
   * 
   * @param rc: the client
   */
  public App(RiscClient rc) {
    this.rc = rc;
  }

  /**
   * function to start the client code
   */
  public static void main(String[] args) throws IOException {
    try {
      RiscClient rc = new RiscClient(new Socket("vcm-30720.vm.duke.edu", 5000));
      App a = new App(rc);
      rc.run();
    } catch (UnknownHostException e) {
      e.printStackTrace();
    }
  }
}
